; PlatformIO - Monitor de Ruido en Aulas
; Hardware: M5Stack Core2 v1.1 (ESP32)

[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino

; Configuracion de compilacion
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_HAS_PSRAM

; Velocidad del monitor serie
monitor_speed = 115200

; Librerias
lib_deps =
    m5stack/M5Unified@^0.2.2
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.2.1

; Particiones con mas espacio para la app
board_build.partitions = default.csv

; Puerto de upload (ajustar segun sistema)
; upload_port = COM3
; monitor_port = COM3
